
-- Generated by ORDS REST Data Services 23.4.1.r0381857
-- Schema: DEMO  Date: Thu Mar 28 08:08:12 2024 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'DEMO',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'demo',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'eu.gpmfactory.custoauth',
      p_base_path      => '/custauth/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'eu.gpmfactory.custoauth',
      p_pattern        => 'redirect',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'eu.gpmfactory.custoauth',
      p_pattern        => 'redirect',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => 'begin',
      p_source         => 
'begin
    :forward_location := ''https://localhots/redirect'';
    :status_code := 302;
end;    ');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'eu.gpmfactory.custoauth',
      p_pattern            => 'redirect',
      p_method             => 'GET',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'eu.gpmfactory.custoauth',
      p_pattern            => 'redirect',
      p_method             => 'GET',
      p_name               => 'Location',
      p_bind_variable_name => 'forward_location',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'eu.gpmfactory.custoauth',
      p_pattern        => 'checktoken',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'a simple test for checking a token passed in the Authorization attribute of header');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'eu.gpmfactory.custoauth',
      p_pattern        => 'checktoken',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'begin
    htp.p(''Token: '' || replace(:authorization, ''Bearer ''));
end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'eu.gpmfactory.custoauth',
      p_pattern            => 'checktoken',
      p_method             => 'GET',
      p_name               => 'authorization',
      p_bind_variable_name => 'Authorization',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'eu.gpmfactory.custoauth',
      p_pattern        => 'auth',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'eu.gpmfactory.custoauth',
      p_pattern        => 'auth',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/x-www-form-urlencoded',
      p_comments       => NULL,
      p_source         => 
'declare
    cr varchar2(100);
    l_url varchar2(2000);
    tref    varchar2(1000);

begin

    tref := OWA_UTIL.get_cgi_env(''HTTP_REFERER'');
    --htp.p(tref);
    begin
    cr := OAUTH_PKG.auth(:client_id, :usr, :pwd, tref);
    exception
    when others then
            :status_code := 403;
    end;
    --client doesn''t exist
    if cr = ''-3'' then
        htp.p(cr); 
    --login failed
    elsif cr = ''-1'' then
        htp.p(cr);
    -- ok, we redirect with the token value    
    else
        begin
            select redirect_uri
            into l_url
            from user_ords_clients
                where client_id= :client_id;
            exception
                when others then
                    cr := ''-4'';
                    --htp.p(cr);
                    :status_code := 403;
        end;
        /*
        begin
        
            for i in 1..nvl(owa.num_cgi_vars, 0) loop
                htp.p(owa.cgi_var_name(i) || '': '' || owa.c' || 'gi_var_val(i) ||''<br>'');
            end loop;
        end;
        */ 
                
        if length(cr) > 5 then
            :forward_location := l_url||''#token=''||cr;
            :status_code := 302;
        else
            :status_code := 403;
        end if;
            
    end if;
end;
');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'eu.gpmfactory.custoauth',
      p_pattern            => 'auth',
      p_method             => 'POST',
      p_name               => 'pwd',
      p_bind_variable_name => 'pwd',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'eu.gpmfactory.custoauth',
      p_pattern            => 'auth',
      p_method             => 'POST',
      p_name               => 'usr',
      p_bind_variable_name => 'usr',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'eu.gpmfactory.custoauth',
      p_pattern            => 'auth',
      p_method             => 'POST',
      p_name               => 'client_id',
      p_bind_variable_name => 'client_id',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'eu.gpmfactory.custoauth',
      p_pattern            => 'auth',
      p_method             => 'POST',
      p_name               => 'Location',
      p_bind_variable_name => 'forward_location',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'eu.gpmfactory.custoauth',
      p_pattern            => 'auth',
      p_method             => 'POST',
      p_name               => 'X-ORDS-STATUS-CODE',
      p_bind_variable_name => 'status_code',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'eu.gpmfactory.custoauth',
      p_pattern        => 'login',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'eu.gpmfactory.custoauth',
      p_pattern        => 'login',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select ''text/html'',
''
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <title>Page de Login</title>
    <!-- lien vers la bibliothèque Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

    <div class="container mt-5">
        <div class="col-md-6 offset-md-3">
            <h2 class="text-center mb-4">Login</h2>
            <form method="post" action="/ords/demo/custauth/auth?client_id=''|| :client_id ||''" >
                <div class="form-group">
                    <label for="username">Username:</label>' || '
                    <input type="text" class="form-control" id="usr" name="usr" required>
                </div>

                <div class="form-group">
                    <label for="password">Password:</label>
                    <input type="password" class="form-control" id="pwd" name="pwd" required>
                </div>

                <button type="submit" class="btn btn-primary btn-block">Login</button>
            </form>
        </div>
    </div>
    
</body>
</html>''
from dual');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'eu.gpmfactory.custoauth',
      p_pattern            => 'login',
      p_method             => 'GET',
      p_name               => 'client_id',
      p_bind_variable_name => 'client_id',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

    
        
COMMIT;

END;